---
title: "COVID-19 trends and trajectories"
author:
  - name: Tim Churches 
    affiliation: South Western Sydney Clinical School, UNSW Medicine & Ingham Institute of Applied Medical Research, Liverpool, Sydney, Australia
    affiliation_url: https://swscs.med.unsw.edu.au
  - name: Nick Tierney 
    affiliation: Monash University
    affiliation_url: 
date: 03-20-2020
output:
  html_document:
    toc: true
    toc_depth: 3
    self_contained: true
vignette: >
  %\VignetteIndexEntry{cumulative-cases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache = FALSE,
                      collapse = TRUE
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE)
```

```{r libraries}
library(covidrecon)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tibble)
library(ggplot2)
library(ggthemes)
library(hrbrthemes)
library(gt)
library(deSolve)
library(EpiEstim)
library(incidence)
library(distcrete)
library(epitrix)
library(projections)
library(ggiraph)
library(ggrepel)

version <- "1.8"
version_date <- lubridate::ymd("2020-02-28")

```

https://blog.grattan.edu.au/2020/03/australian-governments-can-choose-to-slow-the-spread-of-coronavirus-but-they-must-act-immediately/

```{r get-latest-data}
covid <- covid_latest()
```

```{r high-incidence-countries}
high_incidence_countries <- covid_high_incidence(covid) %>% 
  mutate(alpha = ifelse(country_region == "Australia", 1, 0.7)) %>% 
  filter(normalised_date >= 0)
```

```{r select-countries}
selected_countries <- c("China",
                        "Singapore",
                        "Japan",
                        "Iran",
                        "Italy",
                        "Spain",
                        "US",
                        "United Kingdom",
                        "Australia",
                        "France",
                        "Korea, South")

```


```{r get-latest-data-highlight}
library(gghighlight)

gg_covid_cumulative(high_incidence_countries)

high_incidence_countries %>% 
  filter(country_region %in% c("Australia", "Italy")) %>% 
  add_country_label() %>% 
  gg_covid_cumulative() +
  geom_covid_country_label() +
  scale_x_continuous(expand = expansion(mult = c(0, 0.2)))
```

```{r highlight-countries}
highlight_countries <- c("Japan",
                         "Korea, South",
                         "Singapore",
                         "Italy",
                         "Iran",
                         "China",
                         "France",
                         "United Kingdom",
                         "Sweden",
                         "Australia")

high_incidence_countries_extra <- high_incidence_countries %>%
  covid_highlight_australia_plus(plus = highlight_countries) %>% 
  add_country_label() %>% 
  filter(normalised_date >= 0,
         country_region != "Cruise Ship")
```

```{r}
gg <- 
ggplot(
  data = high_incidence_countries_extra,
  aes(
    x = normalised_date,
    y = cumulative_cases,
    colour = country_region,
    alpha = alpha,
    # tooltip = country_region,
    # data_id = country_region
  )
) +
  geom_line() +
  geom_covid_country_label() +
  scale_y_log10(labels = scales::comma) +
  scale_alpha(range = c(0.2, 1)) +
  # scale_x_continuous(expand = expansion(add = c(1, 3))) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    y = "Cumulative cases (logarithmic scale)",
    x = "Days since cumulative cases exceeded 100",
    title = paste("COVID-19 epidemic trajectories up to", format(
      max(high_incidence_countries_extra$date), "%d %B %Y"
    )),
    subtitle = "(click on a line to identify country)",
    caption = paste0(
      "CC-BY-SA-NC Tim Churches (UNSW) & Nick Tierney (Monash)\n",
      "Data source: Johns Hopkins University"
    )
  )

gg
```

# Tim's plots

```{r}
high_incidence_countries %>% 
  filter(country_region == "Australia")
```


```{r}
covid <- covid_latest() 

high_incidence_countries
```

```{r}
highlight_countries <- c("Japan", "South Korea",
                          "Singapore", "Italy",
                          "Iran", "China", "France",
                          "UK",
                          "Sweden", "Australia")

high_incidence_countries <- high_incidence_countries %>%
  left_join(high_incidence_countries %>% 
              filter(hit_100) %>%
              mutate(offset = rnum) %>%
              select(country_region, offset)) %>%
  mutate(normalised_date = rnum - offset) %>%
  select(-c(offset)) %>%
  covid_highlight_australia_plus(plus = highlight_countries) %>%
  add_country_label() %>% 
  mutate(cases = case_when(country_region == "Japan" &
                                      date == ymd("2020-01-23") ~ 0,
                                    country_region == "Japan" &
                                      date == ymd("2020-02-06") ~ 3,
                                    country_region == "Japan" &
                                      date == ymd("2020-02-07") ~ 0,
                                    country_region == "Japan" &
                                      date == ymd("2020-03-15") ~ 52,
                                    country_region == "Japan" &
                                      date == ymd("2020-03-16") ~ 0,
                                    TRUE ~ cases))

```

```{r}
high_incidence_countries %>% 
  filter(country_region == "Australia")
```


```{r}
library(changepoint)

change_dates <- tibble(country_region = character(0),
                       ChangeDate = lubridate::ymd())

extract_change_point_mean_var <- function(data){
  changepoint::cpt.meanvar(data$cases, class = FALSE)["cpt"]
}

# high_incidence_change_date <-
# hi_aus <- 
  high_incidence_countries %>%
    # group_by(country_region) %>%
  filter(country_region == "Australia") %>%
  mutate(n_obs = vctrs::vec_size(country_region)) %>% 
    # remove countries with only 4 observations
    filter(n_obs > 4) %>% 
    ungroup() %>% 
    group_nest(country_region) %>% 
    mutate(change_date = map_dbl(data, extract_change_point_mean_var)) %>% 
      unnest(cols = c(data))  %>% 
      select(country_region,
             date,
             normalised_date,
             change_date) %>% 
      filter(normalised_date == change_date) %>% 
  left_join(x = high_incidence_countries,
            y = .)

```

```{r, fig.width=8, fig,height=16}
high_incidence_changes %>% 
  filter(country_region %in% c(highlight_countries, 
                               "US", 
                               "Germany", 
                               "Denmark")) %>%
  # left_join(change_dates) %>%
  ggplot(aes(x = date, 
             y = cases)) +
    geom_line() +
    geom_vline(aes(xintercept = change_date)) +
    facet_grid(country_region ~ ., 
               scales = "free_y")
```

## The "Grattan Institute" plot

```{r, layout="l-page"}
gg <- high_incidence_changes %>%
  filter(normalised_date >= 0,
         country_region != "Cruise Ship") %>%
  ggplot(
    aes(
      x = normalised_date,
      y = cumulative_cases,
      colour = country_region,
      alpha = alpha,
      tooltip = country_region,
      data_id = country_region
    )
  ) +
  geom_line_interactive(size = 1.2) +
  geom_label(
    aes(x = clabel_x, y = clabel_y, label = clabel_value),
    hjust = 0,
    nudge_x = 0.2
  ) +
  scale_y_log10(labels = scales::comma) +
  scale_alpha(range = c(0.2, 1)) +
  expand_limits(x = c(0, max(
    high_incidence_changes$normalised_date
  ) + 5)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    y = "Cumulative cases (logarithmic scale)",
    x = "Days since cumulative cases exceeded 100",
    title = paste("COVID-19 epidemic trajectories up to", format(
      max(high_incidence_changes$date), "%d %B %Y"
    )),
    subtitle = "(click on a line to identify country)",
    caption = paste0(
      "CC BY-NC-SA Tim Churches (UNSW)\n",
      "Data source: Johns Hopkins University"
    )
  )

girafe(ggobj=gg,
       options = list(opts_tooltip(use_stroke = TRUE, opacity=0.7),
                      opts_hover(css = "stroke:black;"),
                      opts_toolbar(position = "topright", saveaspng = TRUE)
                      ))
```

## Instantaneous effective reproduction number

```{r, eval=TRUE, echo=FALSE, fig.height=8, fig.width=8, layout="l-page"}

country_counter <- 0
for (country in unique(high_incidence_changes$country_region)) {
  if (country %in% c("Bahrain", "Cruise Ship", "Iran",
                     "Lebanon", "China") |
      !country %in% c(highlight_countries, "US", "Germany", "Spain")) next

  country_counter <- country_counter + 1
  
  incidence_data <- high_incidence_changes %>%
    mutate(change_date_obj = case_when(
      normalised_date >= change_date ~ date
    )) %>% 
    # filter(country_region == country) %>%
    filter(country_region == "Australia") %>%
    # filter(date >= change_date) %>%
    filter(date >= change_date_obj) %>%
    mutate(I = cases) %>%
    rename(dates = date) %>%
    select(dates, I)

  
  res_parametric_si <- estimate_R(incidence_data,
                                  method = "parametric_si", 
                                  config = make_config(list(mean_si = 5.0, 
                                                            std_si = 3.0)))
                                  
                                  # method="uncertain_si",
                                  # config = make_config(list(
                                  # mean_si = 4.8, std_mean_si = 3.0,
                                  # min_mean_si = 2, max_mean_si = 7.5,
                                  # std_si = 3.0, std_std_si = 1.0,
                                  # min_std_si = 0.5, max_std_si = 4.0,
                                  # n1 = 1000, n2 = 1000)))
                                  # 
  R_df <-  res_parametric_si$R
  R_df <- R_df %>% 
    mutate(country = country)
  R_df$Date <- res_parametric_si$dates[8:length(res_parametric_si$dates)]
  if (country_counter == 1) {
    country_eff_Rs <- R_df
  } else {
    country_eff_Rs <- country_eff_Rs %>%
      bind_rows(R_df)
  }
}


start_dates <- high_incidence_countries %>%
  filter(hit_100 == TRUE) %>%
  rename(country=country_region,
         start_date=Date) %>%
  select(country, start_date)

country_eff_Rs <- country_eff_Rs %>%
  left_join(start_dates) %>%
  filter(Date >= start_date) %>%
  rename(mean_R="Mean(R)")

label_country_eff_Rs <- country_eff_Rs %>%
  arrange(country, Date) %>%
  group_by(country) %>%
  summarise(clabel_x = max(Date),
            clabel_y = last(mean_R)) %>%
  ungroup()
  
```

```{r, fig.height=8, fig.width=8, layout="l-page"}
country_eff_Rs %>%
  ggplot(aes(x=Date, y=mean_R, colour=country)) +
  geom_line(size=1.5) +
  geom_hline(yintercept = 1.0, colour="red") +
  facet_wrap(~country, ncol = 2) +
  scale_y_log10() +
  scale_x_date(date_breaks = "1 week",
               date_labels = "%d %b") +
  labs(title=paste("7-day sliding window of effective reproduction number up to",
                   format(max(country_eff_Rs$Date), "%d %B %Y")),
       subtitle="Outbreak is under control if effective R is under red line",
       x = "End date of 7-day sliding window",
       y="Effective R (log scale)",
       caption=paste0("CC BY-NC-SA Tim Churches (UNSW)\n",
                      "Data source: Johns Hopkins University")) +
  theme_dark() + 
  theme(legend.position = "none") 

```

```{r, fig.height=8, fig.width=8, layout="l-page"}
country_eff_Rs %>%
  ggplot(aes(x=Date, y=mean_R, colour=country)) +
  geom_line(size=1.5) +
  geom_hline(yintercept = 1.0, colour="red") +
  geom_label_repel(data=label_country_eff_Rs,
                   aes(x=clabel_x, y=clabel_y, label=country),
             hjust = 0, nudge_x = 0.2, xlim=c(max(country_eff_Rs$Date) + days(1),
                                              max(country_eff_Rs$Date) + days(5))) +
  scale_y_log10() +
  scale_x_date(date_breaks = "1 week",
               date_labels = "%d %b",
               expand = expansion(add=c(0,5))) +
  scale_colour_viridis_d() +
  labs(title=paste("7-day sliding window of effective reproduction number up to",
                   format(max(country_eff_Rs$Date), "%d %B %Y")),
       subtitle="Outbreak is under control if effective R is under red line",
       x = "End date of 7-day sliding window",
       y="Effective R (log scale)",
       caption=paste0("CC BY-NC-SA Tim Churches (UNSW)\n",
                      "Data source: Johns Hopkins University")) +
  theme_dark() + 
  theme(legend.position = "none") 

```



```{r eval = FALSE}
library(lubridate)

gg + 
  geom_line_interactive(size = 1.2) %>% 
girafe(ggobj = .,
       options = list(
         opts_tooltip(use_stroke = TRUE, opacity = 0.7),
         opts_hover(css = "stroke:black;"),
         opts_toolbar(position = "topright", saveaspng = TRUE)
       ))

hubei_incidence_function_data <- provinces_confirmed_jh %>%
      filter(date >= ymd("2020-01-11")) %>% 
      mutate(HubeiSansWuhan = if_else(
        condition = is.na(HubeiSansWuhan), 
        true = 0, 
        false = HubeiSansWuhan)) %>%
      mutate(incident_cases = ifelse(Date < ymd("2020-02-15"),
                                     Wuhan + HubeiSansWuhan, Hubei)) %>% mutate(date = format(date, 
    "%Y-%m-%d")) %>% 
    select(Date, incident_cases) 
    %>% uncount(incident_cases)
hubei_incidence_object <- incidence(hubei_incidence_function_data$Date)
```

